### ISSUE TITLE
SYKE harvesting throws exception

### ISSUE THREAD

**Issue by Zharktas** [vrk-kpa/opendata#13]
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/srv/ytp/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 191, in command
    fetch_callback(consumer, method, header, body)
  File "/srv/ytp/ckanext-harvest/ckanext/harvest/queue.py", line 409, in fetch_callback
    fetch_and_import_stages(harvester, obj)
  File "/srv/ytp/ckanext-harvest/ckanext/harvest/queue.py", line 426, in fetch_and_import_stages
    success_import = harvester.import_stage(obj)
  File "/srv/ytp/ckanext-spatial/ckanext/spatial/harvesters/base.py", line 565, in import_stage
    'harvest_object': harvest_object,
  File "/srv/ytp/ckanext-ytp_main/ckanext/ytp/plugin.py", line 700, in get_package_dict
    package_dict = unflatten(flattened)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/navl/dictization_functions.py", line 450, in unflatten
    current_pos = current_pos[key]
IndexError: list index out of range

**Comment by bzar** [comment]
Fixed in a7975f6
